# Generated by Django 4.1.2 on 2022-11-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buracos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bu_gravidade', models.IntegerField(choices=[[1, 'Leve'], [2, 'Moderado'], [3, 'Crítico']], default=0, verbose_name='Gravidade')),
                ('bu_rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('bu_bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('bu_status', models.IntegerField(choices=[[0, 'Não Consertado'], [1, 'Consertado']], default=0, max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Buracos',
            },
        ),
    ]
