# Generated by Django 4.1.2 on 2022-11-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buracos',
            name='bu_gravidade',
            field=models.CharField(choices=[['Leve', 'Leve'], ['Moderado', 'Moderado'], ['Critico', 'Crítico']], max_length=100, verbose_name='Gravidade'),
        ),
        migrations.AlterField(
            model_name='buracos',
            name='bu_status',
            field=models.CharField(choices=[['Nao Consertado', 'Não Consertado'], ['Consertado', 'Consertado']], default=0, max_length=20, verbose_name='Status'),
        ),
    ]
