# Generated by Django 4.1.2 on 2022-11-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_buracos_bu_gravidade_alter_buracos_bu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buracos',
            name='bu_gravidade',
            field=models.CharField(choices=[['Leve', 'Leve'], ['Moderada', 'Moderado'], ['Critica', 'Crítico']], max_length=100, verbose_name='Gravidade'),
        ),
    ]
