# Generated by Django 4.1.2 on 2022-11-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_buracos_bu_gravidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buracos',
            name='bu_status',
            field=models.CharField(choices=[['Nao Consertado', 'Não Consertado'], ['Consertado', 'Consertado']], max_length=20, verbose_name='Status'),
        ),
    ]
