# Generated by Django 4.1.2 on 2022-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_buracos_bu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buracos',
            name='bu_quantia',
            field=models.IntegerField(default=1, verbose_name='Quantia'),
        ),
        migrations.AlterField(
            model_name='buracos',
            name='bu_status',
            field=models.CharField(choices=[['Nao Consertado', 'Não Consertado'], ['Consertado', 'Consertado']], default='Não Consertado', max_length=20, verbose_name='Status'),
        ),
    ]
